export const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  PRESCRIPTION_PENDING: 'PRESCRIPTION_PENDING',
  PRESCRIPTION_APPROVED: 'PRESCRIPTION_APPROVED',
  PROCESSING: 'PROCESSING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_STATUS = {
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_METHODS = {
  RAZORPAY: 'RAZORPAY',
  COD: 'COD',
  TEST: 'TEST',
};

export const PRESCRIPTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const EXPENSE_CATEGORIES = {
  DELIVERY: 'DELIVERY',
  RENT: 'RENT',
  ELECTRICITY: 'ELECTRICITY',
  STAFF: 'STAFF',
  PACKAGING: 'PACKAGING',
  MARKETING: 'MARKETING',
  OTHER: 'OTHER',
};

export const INVENTORY_ACTION = {
  STOCK_ADDED: 'STOCK_ADDED',
  STOCK_REMOVED: 'STOCK_REMOVED',
  ORDER_FULFILLED: 'ORDER_FULFILLED',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
};
